### PR TITLE
Use actions/setup-node action in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
### Benefits

- Control Node.js version
- Set up caching

BTW What are supported Node.js versions for tests?

### CODE REVIEW

**Comment by szepeviktor** [comment]
remark: 16+

**Comment by szepeviktor** [comment]
`ubuntu-latest` contains 18.20.2
https://github.com/actions/runner-images/blob/ubuntu22/20240422.1/images/ubuntu/Ubuntu2204-Readme.md#language-and-runtime

**Comment by marekdedic** [comment]
Hi, thanks, but I don't really see why this would be necessary - the package is not intended to be used with the Node runtime, so I don't see a need to test it with multiple Node versions. So I think as long as it works, Node 18 is just fine... Am I missing some other benefit? It seems to me like this would just take longer to run CI and run it with Node 20 instead of 18 (which I don't think has any benefit...)

**Comment by szepeviktor** [comment]
> Am I missing some other benefit?

Maybe built-in caching ...

(+4 seconds!)

**Comment by marekdedic** [comment]
Ok. Thank you for the idea & PR, but I'm not going to merge it for now - seems to add CI runtime & complexity without much clear benefit. It may be needed some time in the future when the Node version becomes a problem, but I think GitHub is going to start migrating to Ubuntu 24.04 in the meantime anyway... Thanks for understanding!

**Pull request closed without merging**
